server:
  port: ${PORT:8080}  # 환경변수 PORT가 없으면 기본 8080 사용

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://centerbeam.proxy.rlwy.net:19372/railway?serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:XLkxFtTmIfrwcbxeOdCtINmKZcVrnFIP}

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
