server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://centerbeam.proxy.rlwy.net:19372/railway?serverTimezone=Asia/Seoul
    username: root
    password: XLkxFtTmIfrwcbxeOdCtINmKZcVrnFIP

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
