server:
  port: 7777

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lynkdb
    username: lynk
    password: lynk

mybatis:
  mapper-locations: mappers/**/*.xml

